[simple_delay]
name = "Simple Delay"

[multi_filter]
name = "Multi Filter"

[freeverb]
name = "Freeverb"

[stereo_vca]
name = "Stereo VCA"

[simple_oscillator]
name = "Simple Oscillator"

[simple_gui]
name = "Simple GUI"